var annotated_dup =
[
    [ "NanoByte", null, [
      [ "Common", "namespace_nano_byte_1_1_common.html", [
        [ "Collections", "namespace_nano_byte_1_1_common_1_1_collections.html", [
          [ "ArrayExtensions", "class_nano_byte_1_1_common_1_1_collections_1_1_array_extensions.html", "class_nano_byte_1_1_common_1_1_collections_1_1_array_extensions" ],
          [ "CollectionExtensions", "class_nano_byte_1_1_common_1_1_collections_1_1_collection_extensions.html", "class_nano_byte_1_1_common_1_1_collections_1_1_collection_extensions" ],
          [ "ConcurrentSet", "class_nano_byte_1_1_common_1_1_collections_1_1_concurrent_set.html", "class_nano_byte_1_1_common_1_1_collections_1_1_concurrent_set" ],
          [ "CultureComparer", "class_nano_byte_1_1_common_1_1_collections_1_1_culture_comparer.html", "class_nano_byte_1_1_common_1_1_collections_1_1_culture_comparer" ],
          [ "DefaultComparer", "class_nano_byte_1_1_common_1_1_collections_1_1_default_comparer.html", "class_nano_byte_1_1_common_1_1_collections_1_1_default_comparer" ],
          [ "DictionaryExtensions", "class_nano_byte_1_1_common_1_1_collections_1_1_dictionary_extensions.html", "class_nano_byte_1_1_common_1_1_collections_1_1_dictionary_extensions" ],
          [ "EnumerableExtensions", "class_nano_byte_1_1_common_1_1_collections_1_1_enumerable_extensions.html", "class_nano_byte_1_1_common_1_1_collections_1_1_enumerable_extensions" ],
          [ "LanguageSet", "class_nano_byte_1_1_common_1_1_collections_1_1_language_set.html", "class_nano_byte_1_1_common_1_1_collections_1_1_language_set" ],
          [ "ListExtensions", "class_nano_byte_1_1_common_1_1_collections_1_1_list_extensions.html", "class_nano_byte_1_1_common_1_1_collections_1_1_list_extensions" ],
          [ "LocalizableString", "class_nano_byte_1_1_common_1_1_collections_1_1_localizable_string.html", "class_nano_byte_1_1_common_1_1_collections_1_1_localizable_string" ],
          [ "LocalizableStringCollection", "class_nano_byte_1_1_common_1_1_collections_1_1_localizable_string_collection.html", "class_nano_byte_1_1_common_1_1_collections_1_1_localizable_string_collection" ],
          [ "MonitoredCollection", "class_nano_byte_1_1_common_1_1_collections_1_1_monitored_collection.html", "class_nano_byte_1_1_common_1_1_collections_1_1_monitored_collection" ],
          [ "MultiDictionary", "class_nano_byte_1_1_common_1_1_collections_1_1_multi_dictionary.html", "class_nano_byte_1_1_common_1_1_collections_1_1_multi_dictionary" ],
          [ "NamedCollection", "class_nano_byte_1_1_common_1_1_collections_1_1_named_collection.html", "class_nano_byte_1_1_common_1_1_collections_1_1_named_collection" ],
          [ "StackExtensions", "class_nano_byte_1_1_common_1_1_collections_1_1_stack_extensions.html", "class_nano_byte_1_1_common_1_1_collections_1_1_stack_extensions" ],
          [ "TransparentCache", "class_nano_byte_1_1_common_1_1_collections_1_1_transparent_cache.html", "class_nano_byte_1_1_common_1_1_collections_1_1_transparent_cache" ],
          [ "TransparentCacheBase", "class_nano_byte_1_1_common_1_1_collections_1_1_transparent_cache_base.html", "class_nano_byte_1_1_common_1_1_collections_1_1_transparent_cache_base" ],
          [ "XmlDictionary", "class_nano_byte_1_1_common_1_1_collections_1_1_xml_dictionary.html", "class_nano_byte_1_1_common_1_1_collections_1_1_xml_dictionary" ],
          [ "XmlDictionaryEntry", "class_nano_byte_1_1_common_1_1_collections_1_1_xml_dictionary_entry.html", "class_nano_byte_1_1_common_1_1_collections_1_1_xml_dictionary_entry" ]
        ] ],
        [ "Controls", "namespace_nano_byte_1_1_common_1_1_controls.html", [
          [ "ControlExtensions", "class_nano_byte_1_1_common_1_1_controls_1_1_control_extensions.html", "class_nano_byte_1_1_common_1_1_controls_1_1_control_extensions" ],
          [ "DropDownButton", "class_nano_byte_1_1_common_1_1_controls_1_1_drop_down_button.html", "class_nano_byte_1_1_common_1_1_controls_1_1_drop_down_button" ],
          [ "ErrorBox", "class_nano_byte_1_1_common_1_1_controls_1_1_error_box.html", "class_nano_byte_1_1_common_1_1_controls_1_1_error_box" ],
          [ "ErrorReportForm", "class_nano_byte_1_1_common_1_1_controls_1_1_error_report_form.html", "class_nano_byte_1_1_common_1_1_controls_1_1_error_report_form" ],
          [ "ErrorReport", "class_nano_byte_1_1_common_1_1_controls_1_1_error_report.html", "class_nano_byte_1_1_common_1_1_controls_1_1_error_report" ],
          [ "FilteredTreeView", "class_nano_byte_1_1_common_1_1_controls_1_1_filtered_tree_view.html", "class_nano_byte_1_1_common_1_1_controls_1_1_filtered_tree_view" ],
          [ "HintTextBox", "class_nano_byte_1_1_common_1_1_controls_1_1_hint_text_box.html", "class_nano_byte_1_1_common_1_1_controls_1_1_hint_text_box" ],
          [ "IContextMenu", "interface_nano_byte_1_1_common_1_1_controls_1_1_i_context_menu.html", "interface_nano_byte_1_1_common_1_1_controls_1_1_i_context_menu" ],
          [ "IEditorDialog", "interface_nano_byte_1_1_common_1_1_controls_1_1_i_editor_dialog.html", "interface_nano_byte_1_1_common_1_1_controls_1_1_i_editor_dialog" ],
          [ "InputBox", "class_nano_byte_1_1_common_1_1_controls_1_1_input_box.html", "class_nano_byte_1_1_common_1_1_controls_1_1_input_box" ],
          [ "ITouchControl", "interface_nano_byte_1_1_common_1_1_controls_1_1_i_touch_control.html", "interface_nano_byte_1_1_common_1_1_controls_1_1_i_touch_control" ],
          [ "Msg", "class_nano_byte_1_1_common_1_1_controls_1_1_msg.html", "class_nano_byte_1_1_common_1_1_controls_1_1_msg" ],
          [ "OKCancelDialog", "class_nano_byte_1_1_common_1_1_controls_1_1_o_k_cancel_dialog.html", "class_nano_byte_1_1_common_1_1_controls_1_1_o_k_cancel_dialog" ],
          [ "OutputBox", "class_nano_byte_1_1_common_1_1_controls_1_1_output_box.html", "class_nano_byte_1_1_common_1_1_controls_1_1_output_box" ],
          [ "OutputGridBox", "class_nano_byte_1_1_common_1_1_controls_1_1_output_grid_box.html", "class_nano_byte_1_1_common_1_1_controls_1_1_output_grid_box" ],
          [ "OutputTreeBox", "class_nano_byte_1_1_common_1_1_controls_1_1_output_tree_box.html", "class_nano_byte_1_1_common_1_1_controls_1_1_output_tree_box" ],
          [ "PropertyGridForm", "class_nano_byte_1_1_common_1_1_controls_1_1_property_grid_form.html", "class_nano_byte_1_1_common_1_1_controls_1_1_property_grid_form" ],
          [ "ResettablePropertyGrid", "class_nano_byte_1_1_common_1_1_controls_1_1_resettable_property_grid.html", "class_nano_byte_1_1_common_1_1_controls_1_1_resettable_property_grid" ],
          [ "RtfBuilder", "class_nano_byte_1_1_common_1_1_controls_1_1_rtf_builder.html", "class_nano_byte_1_1_common_1_1_controls_1_1_rtf_builder" ],
          [ "TaskControl", "class_nano_byte_1_1_common_1_1_controls_1_1_task_control.html", "class_nano_byte_1_1_common_1_1_controls_1_1_task_control" ],
          [ "TaskLabel", "class_nano_byte_1_1_common_1_1_controls_1_1_task_label.html", "class_nano_byte_1_1_common_1_1_controls_1_1_task_label" ],
          [ "TaskProgressBar", "class_nano_byte_1_1_common_1_1_controls_1_1_task_progress_bar.html", "class_nano_byte_1_1_common_1_1_controls_1_1_task_progress_bar" ],
          [ "TimeSpanControl", "class_nano_byte_1_1_common_1_1_controls_1_1_time_span_control.html", "class_nano_byte_1_1_common_1_1_controls_1_1_time_span_control" ],
          [ "TouchEventArgs", "class_nano_byte_1_1_common_1_1_controls_1_1_touch_event_args.html", "class_nano_byte_1_1_common_1_1_controls_1_1_touch_event_args" ],
          [ "TouchForm", "class_nano_byte_1_1_common_1_1_controls_1_1_touch_form.html", "class_nano_byte_1_1_common_1_1_controls_1_1_touch_form" ],
          [ "TouchPanel", "class_nano_byte_1_1_common_1_1_controls_1_1_touch_panel.html", "class_nano_byte_1_1_common_1_1_controls_1_1_touch_panel" ],
          [ "UriTextBox", "class_nano_byte_1_1_common_1_1_controls_1_1_uri_text_box.html", "class_nano_byte_1_1_common_1_1_controls_1_1_uri_text_box" ]
        ] ],
        [ "Dispatch", "namespace_nano_byte_1_1_common_1_1_dispatch.html", [
          [ "AggregateDispatcher", "class_nano_byte_1_1_common_1_1_dispatch_1_1_aggregate_dispatcher.html", "class_nano_byte_1_1_common_1_1_dispatch_1_1_aggregate_dispatcher" ],
          [ "Bucketizer", "class_nano_byte_1_1_common_1_1_dispatch_1_1_bucketizer.html", "class_nano_byte_1_1_common_1_1_dispatch_1_1_bucketizer" ],
          [ "BucketRule", "class_nano_byte_1_1_common_1_1_dispatch_1_1_bucket_rule.html", "class_nano_byte_1_1_common_1_1_dispatch_1_1_bucket_rule" ],
          [ "IChangeNotify", "interface_nano_byte_1_1_common_1_1_dispatch_1_1_i_change_notify.html", "interface_nano_byte_1_1_common_1_1_dispatch_1_1_i_change_notify" ],
          [ "IMergeable", "interface_nano_byte_1_1_common_1_1_dispatch_1_1_i_mergeable.html", "interface_nano_byte_1_1_common_1_1_dispatch_1_1_i_mergeable" ],
          [ "Merge", "class_nano_byte_1_1_common_1_1_dispatch_1_1_merge.html", "class_nano_byte_1_1_common_1_1_dispatch_1_1_merge" ],
          [ "ModelViewSync", "class_nano_byte_1_1_common_1_1_dispatch_1_1_model_view_sync.html", "class_nano_byte_1_1_common_1_1_dispatch_1_1_model_view_sync" ],
          [ "PerTypeDispatcher", "class_nano_byte_1_1_common_1_1_dispatch_1_1_per_type_dispatcher.html", "class_nano_byte_1_1_common_1_1_dispatch_1_1_per_type_dispatcher" ]
        ] ],
        [ "Drawing", "namespace_nano_byte_1_1_common_1_1_drawing.html", [
          [ "ImageExtensions", "class_nano_byte_1_1_common_1_1_drawing_1_1_image_extensions.html", "class_nano_byte_1_1_common_1_1_drawing_1_1_image_extensions" ],
          [ "ScalableImage", "class_nano_byte_1_1_common_1_1_drawing_1_1_scalable_image.html", "class_nano_byte_1_1_common_1_1_drawing_1_1_scalable_image" ]
        ] ],
        [ "Info", "namespace_nano_byte_1_1_common_1_1_info.html", [
          [ "AppInfo", "struct_nano_byte_1_1_common_1_1_info_1_1_app_info.html", "struct_nano_byte_1_1_common_1_1_info_1_1_app_info" ],
          [ "ExceptionInfo", "class_nano_byte_1_1_common_1_1_info_1_1_exception_info.html", "class_nano_byte_1_1_common_1_1_info_1_1_exception_info" ],
          [ "OSInfo", "struct_nano_byte_1_1_common_1_1_info_1_1_o_s_info.html", "struct_nano_byte_1_1_common_1_1_info_1_1_o_s_info" ]
        ] ],
        [ "Native", "namespace_nano_byte_1_1_common_1_1_native.html", [
          [ "AppMutex", "class_nano_byte_1_1_common_1_1_native_1_1_app_mutex.html", "class_nano_byte_1_1_common_1_1_native_1_1_app_mutex" ],
          [ "CygwinUtils", "class_nano_byte_1_1_common_1_1_native_1_1_cygwin_utils.html", "class_nano_byte_1_1_common_1_1_native_1_1_cygwin_utils" ],
          [ "OSUtils", "class_nano_byte_1_1_common_1_1_native_1_1_o_s_utils.html", "class_nano_byte_1_1_common_1_1_native_1_1_o_s_utils" ],
          [ "RegistryUtils", "class_nano_byte_1_1_common_1_1_native_1_1_registry_utils.html", "class_nano_byte_1_1_common_1_1_native_1_1_registry_utils" ],
          [ "UnixUtils", "class_nano_byte_1_1_common_1_1_native_1_1_unix_utils.html", "class_nano_byte_1_1_common_1_1_native_1_1_unix_utils" ],
          [ "WindowsCredentials", "class_nano_byte_1_1_common_1_1_native_1_1_windows_credentials.html", "class_nano_byte_1_1_common_1_1_native_1_1_windows_credentials" ],
          [ "WindowsMutex", "class_nano_byte_1_1_common_1_1_native_1_1_windows_mutex.html", "class_nano_byte_1_1_common_1_1_native_1_1_windows_mutex" ],
          [ "WindowsRestartManager", "class_nano_byte_1_1_common_1_1_native_1_1_windows_restart_manager.html", "class_nano_byte_1_1_common_1_1_native_1_1_windows_restart_manager" ],
          [ "WindowsTaskbar", "class_nano_byte_1_1_common_1_1_native_1_1_windows_taskbar.html", "class_nano_byte_1_1_common_1_1_native_1_1_windows_taskbar" ],
          [ "WindowsUtils", "class_nano_byte_1_1_common_1_1_native_1_1_windows_utils.html", "class_nano_byte_1_1_common_1_1_native_1_1_windows_utils" ],
          [ "WinFormsUtils", "class_nano_byte_1_1_common_1_1_native_1_1_win_forms_utils.html", "class_nano_byte_1_1_common_1_1_native_1_1_win_forms_utils" ]
        ] ],
        [ "Net", "namespace_nano_byte_1_1_common_1_1_net.html", [
          [ "CachedCredentialProvider", "class_nano_byte_1_1_common_1_1_net_1_1_cached_credential_provider.html", "class_nano_byte_1_1_common_1_1_net_1_1_cached_credential_provider" ],
          [ "ConfigurationCredentialProvider", "class_nano_byte_1_1_common_1_1_net_1_1_configuration_credential_provider.html", "class_nano_byte_1_1_common_1_1_net_1_1_configuration_credential_provider" ],
          [ "ConfigurationCredentialProviderRegistration", "class_nano_byte_1_1_common_1_1_net_1_1_configuration_credential_provider_registration.html", "class_nano_byte_1_1_common_1_1_net_1_1_configuration_credential_provider_registration" ],
          [ "CredentialProviderBase", "class_nano_byte_1_1_common_1_1_net_1_1_credential_provider_base.html", "class_nano_byte_1_1_common_1_1_net_1_1_credential_provider_base" ],
          [ "DownloadFile", "class_nano_byte_1_1_common_1_1_net_1_1_download_file.html", "class_nano_byte_1_1_common_1_1_net_1_1_download_file" ],
          [ "ICredentialProvider", "interface_nano_byte_1_1_common_1_1_net_1_1_i_credential_provider.html", "interface_nano_byte_1_1_common_1_1_net_1_1_i_credential_provider" ],
          [ "MicroServer", "class_nano_byte_1_1_common_1_1_net_1_1_micro_server.html", "class_nano_byte_1_1_common_1_1_net_1_1_micro_server" ],
          [ "NetUtils", "class_nano_byte_1_1_common_1_1_net_1_1_net_utils.html", "class_nano_byte_1_1_common_1_1_net_1_1_net_utils" ],
          [ "UriExtensions", "class_nano_byte_1_1_common_1_1_net_1_1_uri_extensions.html", "class_nano_byte_1_1_common_1_1_net_1_1_uri_extensions" ],
          [ "WebClientTimeout", "class_nano_byte_1_1_common_1_1_net_1_1_web_client_timeout.html", "class_nano_byte_1_1_common_1_1_net_1_1_web_client_timeout" ],
          [ "WindowsCliCredentialProvider", "class_nano_byte_1_1_common_1_1_net_1_1_windows_cli_credential_provider.html", "class_nano_byte_1_1_common_1_1_net_1_1_windows_cli_credential_provider" ],
          [ "WindowsCredentialProvider", "class_nano_byte_1_1_common_1_1_net_1_1_windows_credential_provider.html", "class_nano_byte_1_1_common_1_1_net_1_1_windows_credential_provider" ],
          [ "WindowsGuiCredentialProvider", "class_nano_byte_1_1_common_1_1_net_1_1_windows_gui_credential_provider.html", "class_nano_byte_1_1_common_1_1_net_1_1_windows_gui_credential_provider" ],
          [ "WindowsSilentCredentialProvider", "class_nano_byte_1_1_common_1_1_net_1_1_windows_silent_credential_provider.html", "class_nano_byte_1_1_common_1_1_net_1_1_windows_silent_credential_provider" ],
          [ "AnsiCliCredentialProvider", "class_nano_byte_1_1_common_1_1_net_1_1_ansi_cli_credential_provider.html", "class_nano_byte_1_1_common_1_1_net_1_1_ansi_cli_credential_provider" ]
        ] ],
        [ "Storage", "namespace_nano_byte_1_1_common_1_1_storage.html", [
          [ "AtomicRead", "class_nano_byte_1_1_common_1_1_storage_1_1_atomic_read.html", "class_nano_byte_1_1_common_1_1_storage_1_1_atomic_read" ],
          [ "AtomicWrite", "class_nano_byte_1_1_common_1_1_storage_1_1_atomic_write.html", "class_nano_byte_1_1_common_1_1_storage_1_1_atomic_write" ],
          [ "BinaryStorage", "class_nano_byte_1_1_common_1_1_storage_1_1_binary_storage.html", "class_nano_byte_1_1_common_1_1_storage_1_1_binary_storage" ],
          [ "CopyDirectory", "class_nano_byte_1_1_common_1_1_storage_1_1_copy_directory.html", "class_nano_byte_1_1_common_1_1_storage_1_1_copy_directory" ],
          [ "FileUtils", "class_nano_byte_1_1_common_1_1_storage_1_1_file_utils.html", "class_nano_byte_1_1_common_1_1_storage_1_1_file_utils" ],
          [ "JsonStorage", "class_nano_byte_1_1_common_1_1_storage_1_1_json_storage.html", "class_nano_byte_1_1_common_1_1_storage_1_1_json_storage" ],
          [ "Locations", "class_nano_byte_1_1_common_1_1_storage_1_1_locations.html", "class_nano_byte_1_1_common_1_1_storage_1_1_locations" ],
          [ "LocationsRedirect", "class_nano_byte_1_1_common_1_1_storage_1_1_locations_redirect.html", "class_nano_byte_1_1_common_1_1_storage_1_1_locations_redirect" ],
          [ "MoveDirectory", "class_nano_byte_1_1_common_1_1_storage_1_1_move_directory.html", "class_nano_byte_1_1_common_1_1_storage_1_1_move_directory" ],
          [ "Paths", "class_nano_byte_1_1_common_1_1_storage_1_1_paths.html", "class_nano_byte_1_1_common_1_1_storage_1_1_paths" ],
          [ "ReadFile", "class_nano_byte_1_1_common_1_1_storage_1_1_read_file.html", "class_nano_byte_1_1_common_1_1_storage_1_1_read_file" ],
          [ "TemporaryDirectory", "class_nano_byte_1_1_common_1_1_storage_1_1_temporary_directory.html", "class_nano_byte_1_1_common_1_1_storage_1_1_temporary_directory" ],
          [ "TemporaryFile", "class_nano_byte_1_1_common_1_1_storage_1_1_temporary_file.html", "class_nano_byte_1_1_common_1_1_storage_1_1_temporary_file" ],
          [ "TemporaryFlagFile", "class_nano_byte_1_1_common_1_1_storage_1_1_temporary_flag_file.html", "class_nano_byte_1_1_common_1_1_storage_1_1_temporary_flag_file" ],
          [ "TemporaryWorkingDirectory", "class_nano_byte_1_1_common_1_1_storage_1_1_temporary_working_directory.html", "class_nano_byte_1_1_common_1_1_storage_1_1_temporary_working_directory" ],
          [ "WorkingDirectory", "class_nano_byte_1_1_common_1_1_storage_1_1_working_directory.html", "class_nano_byte_1_1_common_1_1_storage_1_1_working_directory" ],
          [ "XmlNamespaceAttribute", "class_nano_byte_1_1_common_1_1_storage_1_1_xml_namespace_attribute.html", "class_nano_byte_1_1_common_1_1_storage_1_1_xml_namespace_attribute" ],
          [ "XmlStorage", "class_nano_byte_1_1_common_1_1_storage_1_1_xml_storage.html", "class_nano_byte_1_1_common_1_1_storage_1_1_xml_storage" ]
        ] ],
        [ "Streams", "namespace_nano_byte_1_1_common_1_1_streams.html", [
          [ "ChildProcess", "class_nano_byte_1_1_common_1_1_streams_1_1_child_process.html", "class_nano_byte_1_1_common_1_1_streams_1_1_child_process" ],
          [ "DelegatingStream", "class_nano_byte_1_1_common_1_1_streams_1_1_delegating_stream.html", "class_nano_byte_1_1_common_1_1_streams_1_1_delegating_stream" ],
          [ "ExtraDisposeStream", "class_nano_byte_1_1_common_1_1_streams_1_1_extra_dispose_stream.html", "class_nano_byte_1_1_common_1_1_streams_1_1_extra_dispose_stream" ],
          [ "OffsetStream", "class_nano_byte_1_1_common_1_1_streams_1_1_offset_stream.html", "class_nano_byte_1_1_common_1_1_streams_1_1_offset_stream" ],
          [ "ProducerConsumerStream", "class_nano_byte_1_1_common_1_1_streams_1_1_producer_consumer_stream.html", "class_nano_byte_1_1_common_1_1_streams_1_1_producer_consumer_stream" ],
          [ "ProgressStream", "class_nano_byte_1_1_common_1_1_streams_1_1_progress_stream.html", "class_nano_byte_1_1_common_1_1_streams_1_1_progress_stream" ],
          [ "ShadowingStream", "class_nano_byte_1_1_common_1_1_streams_1_1_shadowing_stream.html", "class_nano_byte_1_1_common_1_1_streams_1_1_shadowing_stream" ],
          [ "StreamConsumer", "class_nano_byte_1_1_common_1_1_streams_1_1_stream_consumer.html", "class_nano_byte_1_1_common_1_1_streams_1_1_stream_consumer" ],
          [ "StreamUtils", "class_nano_byte_1_1_common_1_1_streams_1_1_stream_utils.html", "class_nano_byte_1_1_common_1_1_streams_1_1_stream_utils" ]
        ] ],
        [ "Tasks", "namespace_nano_byte_1_1_common_1_1_tasks.html", [
          [ "CliProgress", "class_nano_byte_1_1_common_1_1_tasks_1_1_cli_progress.html", "class_nano_byte_1_1_common_1_1_tasks_1_1_cli_progress" ],
          [ "CliTaskHandler", "class_nano_byte_1_1_common_1_1_tasks_1_1_cli_task_handler.html", "class_nano_byte_1_1_common_1_1_tasks_1_1_cli_task_handler" ],
          [ "ForEachTask", "class_nano_byte_1_1_common_1_1_tasks_1_1_for_each_task.html", "class_nano_byte_1_1_common_1_1_tasks_1_1_for_each_task" ],
          [ "ITask", "interface_nano_byte_1_1_common_1_1_tasks_1_1_i_task.html", "interface_nano_byte_1_1_common_1_1_tasks_1_1_i_task" ],
          [ "ITaskHandler", "interface_nano_byte_1_1_common_1_1_tasks_1_1_i_task_handler.html", "interface_nano_byte_1_1_common_1_1_tasks_1_1_i_task_handler" ],
          [ "ServiceTaskHandler", "class_nano_byte_1_1_common_1_1_tasks_1_1_service_task_handler.html", "class_nano_byte_1_1_common_1_1_tasks_1_1_service_task_handler" ],
          [ "SilentTaskHandler", "class_nano_byte_1_1_common_1_1_tasks_1_1_silent_task_handler.html", "class_nano_byte_1_1_common_1_1_tasks_1_1_silent_task_handler" ],
          [ "SimplePercentTask", "class_nano_byte_1_1_common_1_1_tasks_1_1_simple_percent_task.html", "class_nano_byte_1_1_common_1_1_tasks_1_1_simple_percent_task" ],
          [ "SimpleTask", "class_nano_byte_1_1_common_1_1_tasks_1_1_simple_task.html", "class_nano_byte_1_1_common_1_1_tasks_1_1_simple_task" ],
          [ "TaskBase", "class_nano_byte_1_1_common_1_1_tasks_1_1_task_base.html", "class_nano_byte_1_1_common_1_1_tasks_1_1_task_base" ],
          [ "TaskHandlerBase", "class_nano_byte_1_1_common_1_1_tasks_1_1_task_handler_base.html", "class_nano_byte_1_1_common_1_1_tasks_1_1_task_handler_base" ],
          [ "TaskHandlerExtensions", "class_nano_byte_1_1_common_1_1_tasks_1_1_task_handler_extensions.html", "class_nano_byte_1_1_common_1_1_tasks_1_1_task_handler_extensions" ],
          [ "TaskSnapshot", "struct_nano_byte_1_1_common_1_1_tasks_1_1_task_snapshot.html", "struct_nano_byte_1_1_common_1_1_tasks_1_1_task_snapshot" ],
          [ "AnsiCliProgress", "class_nano_byte_1_1_common_1_1_tasks_1_1_ansi_cli_progress.html", "class_nano_byte_1_1_common_1_1_tasks_1_1_ansi_cli_progress" ],
          [ "AnsiCliProgressContext", "class_nano_byte_1_1_common_1_1_tasks_1_1_ansi_cli_progress_context.html", "class_nano_byte_1_1_common_1_1_tasks_1_1_ansi_cli_progress_context" ],
          [ "AnsiCliTaskHandler", "class_nano_byte_1_1_common_1_1_tasks_1_1_ansi_cli_task_handler.html", "class_nano_byte_1_1_common_1_1_tasks_1_1_ansi_cli_task_handler" ],
          [ "DialogTaskHandler", "class_nano_byte_1_1_common_1_1_tasks_1_1_dialog_task_handler.html", "class_nano_byte_1_1_common_1_1_tasks_1_1_dialog_task_handler" ],
          [ "GuiTaskHandlerBase", "class_nano_byte_1_1_common_1_1_tasks_1_1_gui_task_handler_base.html", "class_nano_byte_1_1_common_1_1_tasks_1_1_gui_task_handler_base" ],
          [ "TaskRunDialog", "class_nano_byte_1_1_common_1_1_tasks_1_1_task_run_dialog.html", "class_nano_byte_1_1_common_1_1_tasks_1_1_task_run_dialog" ]
        ] ],
        [ "Threading", "namespace_nano_byte_1_1_common_1_1_threading.html", [
          [ "ActionExtensions", "class_nano_byte_1_1_common_1_1_threading_1_1_action_extensions.html", "class_nano_byte_1_1_common_1_1_threading_1_1_action_extensions" ],
          [ "CancellationGuard", "class_nano_byte_1_1_common_1_1_threading_1_1_cancellation_guard.html", "class_nano_byte_1_1_common_1_1_threading_1_1_cancellation_guard" ],
          [ "FuncExtensions", "class_nano_byte_1_1_common_1_1_threading_1_1_func_extensions.html", "class_nano_byte_1_1_common_1_1_threading_1_1_func_extensions" ],
          [ "MarshalNoTimeout", "class_nano_byte_1_1_common_1_1_threading_1_1_marshal_no_timeout.html", "class_nano_byte_1_1_common_1_1_threading_1_1_marshal_no_timeout" ],
          [ "MutexLock", "class_nano_byte_1_1_common_1_1_threading_1_1_mutex_lock.html", "class_nano_byte_1_1_common_1_1_threading_1_1_mutex_lock" ],
          [ "SynchronousProgress", "class_nano_byte_1_1_common_1_1_threading_1_1_synchronous_progress.html", "class_nano_byte_1_1_common_1_1_threading_1_1_synchronous_progress" ],
          [ "ThreadUtils", "class_nano_byte_1_1_common_1_1_threading_1_1_thread_utils.html", "class_nano_byte_1_1_common_1_1_threading_1_1_thread_utils" ],
          [ "WaitHandleExtensions", "class_nano_byte_1_1_common_1_1_threading_1_1_wait_handle_extensions.html", "class_nano_byte_1_1_common_1_1_threading_1_1_wait_handle_extensions" ],
          [ "WaitTask", "class_nano_byte_1_1_common_1_1_threading_1_1_wait_task.html", "class_nano_byte_1_1_common_1_1_threading_1_1_wait_task" ],
          [ "AsyncFormWrapper", "class_nano_byte_1_1_common_1_1_threading_1_1_async_form_wrapper.html", "class_nano_byte_1_1_common_1_1_threading_1_1_async_form_wrapper" ]
        ] ],
        [ "Undo", "namespace_nano_byte_1_1_common_1_1_undo.html", [
          [ "AddToCollection", "class_nano_byte_1_1_common_1_1_undo_1_1_add_to_collection.html", "class_nano_byte_1_1_common_1_1_undo_1_1_add_to_collection" ],
          [ "CollectionCommand", "class_nano_byte_1_1_common_1_1_undo_1_1_collection_command.html", "class_nano_byte_1_1_common_1_1_undo_1_1_collection_command" ],
          [ "CommandCollector", "class_nano_byte_1_1_common_1_1_undo_1_1_command_collector.html", "class_nano_byte_1_1_common_1_1_undo_1_1_command_collector" ],
          [ "CommandManager", "class_nano_byte_1_1_common_1_1_undo_1_1_command_manager.html", "class_nano_byte_1_1_common_1_1_undo_1_1_command_manager" ],
          [ "CompositeCommand", "class_nano_byte_1_1_common_1_1_undo_1_1_composite_command.html", "class_nano_byte_1_1_common_1_1_undo_1_1_composite_command" ],
          [ "FirstExecuteCommand", "class_nano_byte_1_1_common_1_1_undo_1_1_first_execute_command.html", "class_nano_byte_1_1_common_1_1_undo_1_1_first_execute_command" ],
          [ "ICommandExecutor", "interface_nano_byte_1_1_common_1_1_undo_1_1_i_command_executor.html", "interface_nano_byte_1_1_common_1_1_undo_1_1_i_command_executor" ],
          [ "ICommandManager", "interface_nano_byte_1_1_common_1_1_undo_1_1_i_command_manager.html", "interface_nano_byte_1_1_common_1_1_undo_1_1_i_command_manager" ],
          [ "IUndoCommand", "interface_nano_byte_1_1_common_1_1_undo_1_1_i_undo_command.html", "interface_nano_byte_1_1_common_1_1_undo_1_1_i_undo_command" ],
          [ "IValueCommand", "interface_nano_byte_1_1_common_1_1_undo_1_1_i_value_command.html", "interface_nano_byte_1_1_common_1_1_undo_1_1_i_value_command" ],
          [ "PreExecutedCommand", "class_nano_byte_1_1_common_1_1_undo_1_1_pre_executed_command.html", "class_nano_byte_1_1_common_1_1_undo_1_1_pre_executed_command" ],
          [ "PreExecutedCompositeCommand", "class_nano_byte_1_1_common_1_1_undo_1_1_pre_executed_composite_command.html", "class_nano_byte_1_1_common_1_1_undo_1_1_pre_executed_composite_command" ],
          [ "RemoveFromCollection", "class_nano_byte_1_1_common_1_1_undo_1_1_remove_from_collection.html", "class_nano_byte_1_1_common_1_1_undo_1_1_remove_from_collection" ],
          [ "ReplaceInList", "class_nano_byte_1_1_common_1_1_undo_1_1_replace_in_list.html", "class_nano_byte_1_1_common_1_1_undo_1_1_replace_in_list" ],
          [ "SetInList", "class_nano_byte_1_1_common_1_1_undo_1_1_set_in_list.html", "class_nano_byte_1_1_common_1_1_undo_1_1_set_in_list" ],
          [ "SetLocalizableString", "class_nano_byte_1_1_common_1_1_undo_1_1_set_localizable_string.html", "class_nano_byte_1_1_common_1_1_undo_1_1_set_localizable_string" ],
          [ "SetValueCommand", "class_nano_byte_1_1_common_1_1_undo_1_1_set_value_command.html", "class_nano_byte_1_1_common_1_1_undo_1_1_set_value_command" ],
          [ "SimpleCommand", "class_nano_byte_1_1_common_1_1_undo_1_1_simple_command.html", "class_nano_byte_1_1_common_1_1_undo_1_1_simple_command" ],
          [ "SimpleCommandExecutor", "class_nano_byte_1_1_common_1_1_undo_1_1_simple_command_executor.html", "class_nano_byte_1_1_common_1_1_undo_1_1_simple_command_executor" ],
          [ "MultiPropertyChangedCommand", "class_nano_byte_1_1_common_1_1_undo_1_1_multi_property_changed_command.html", "class_nano_byte_1_1_common_1_1_undo_1_1_multi_property_changed_command" ],
          [ "MultiPropertyTracker", "class_nano_byte_1_1_common_1_1_undo_1_1_multi_property_tracker.html", "class_nano_byte_1_1_common_1_1_undo_1_1_multi_property_tracker" ],
          [ "PropertyChangedCommand", "class_nano_byte_1_1_common_1_1_undo_1_1_property_changed_command.html", "class_nano_byte_1_1_common_1_1_undo_1_1_property_changed_command" ]
        ] ],
        [ "Values", "namespace_nano_byte_1_1_common_1_1_values.html", [
          [ "Design", "namespace_nano_byte_1_1_common_1_1_values_1_1_design.html", [
            [ "EnumDescriptionConverter", "class_nano_byte_1_1_common_1_1_values_1_1_design_1_1_enum_description_converter.html", "class_nano_byte_1_1_common_1_1_values_1_1_design_1_1_enum_description_converter" ],
            [ "EnumXmlConverter", "class_nano_byte_1_1_common_1_1_values_1_1_design_1_1_enum_xml_converter.html", "class_nano_byte_1_1_common_1_1_values_1_1_design_1_1_enum_xml_converter" ],
            [ "StringConstructorConverter", "class_nano_byte_1_1_common_1_1_values_1_1_design_1_1_string_constructor_converter.html", "class_nano_byte_1_1_common_1_1_values_1_1_design_1_1_string_constructor_converter" ],
            [ "ValueTypeConverter", "class_nano_byte_1_1_common_1_1_values_1_1_design_1_1_value_type_converter.html", "class_nano_byte_1_1_common_1_1_values_1_1_design_1_1_value_type_converter" ],
            [ "LanguageSetEditor", "class_nano_byte_1_1_common_1_1_values_1_1_design_1_1_language_set_editor.html", "class_nano_byte_1_1_common_1_1_values_1_1_design_1_1_language_set_editor" ],
            [ "TimeSpanEditor", "class_nano_byte_1_1_common_1_1_values_1_1_design_1_1_time_span_editor.html", "class_nano_byte_1_1_common_1_1_values_1_1_design_1_1_time_span_editor" ]
          ] ],
          [ "AttributeUtils", "class_nano_byte_1_1_common_1_1_values_1_1_attribute_utils.html", "class_nano_byte_1_1_common_1_1_values_1_1_attribute_utils" ],
          [ "EnumExtensions", "class_nano_byte_1_1_common_1_1_values_1_1_enum_extensions.html", "class_nano_byte_1_1_common_1_1_values_1_1_enum_extensions" ],
          [ "KeyEqualityComparer", "class_nano_byte_1_1_common_1_1_values_1_1_key_equality_comparer.html", "class_nano_byte_1_1_common_1_1_values_1_1_key_equality_comparer" ],
          [ "Languages", "class_nano_byte_1_1_common_1_1_values_1_1_languages.html", "class_nano_byte_1_1_common_1_1_values_1_1_languages" ]
        ] ],
        [ "Disposable", "class_nano_byte_1_1_common_1_1_disposable.html", "class_nano_byte_1_1_common_1_1_disposable" ],
        [ "EncodingUtils", "class_nano_byte_1_1_common_1_1_encoding_utils.html", "class_nano_byte_1_1_common_1_1_encoding_utils" ],
        [ "ExceptionUtils", "class_nano_byte_1_1_common_1_1_exception_utils.html", "class_nano_byte_1_1_common_1_1_exception_utils" ],
        [ "ICloneable", "interface_nano_byte_1_1_common_1_1_i_cloneable.html", "interface_nano_byte_1_1_common_1_1_i_cloneable" ],
        [ "IHighlightColor", "interface_nano_byte_1_1_common_1_1_i_highlight_color.html", "interface_nano_byte_1_1_common_1_1_i_highlight_color" ],
        [ "INamed", "interface_nano_byte_1_1_common_1_1_i_named.html", "interface_nano_byte_1_1_common_1_1_i_named" ],
        [ "Named", "class_nano_byte_1_1_common_1_1_named.html", "class_nano_byte_1_1_common_1_1_named" ],
        [ "Log", "class_nano_byte_1_1_common_1_1_log.html", "class_nano_byte_1_1_common_1_1_log" ],
        [ "MathUtils", "class_nano_byte_1_1_common_1_1_math_utils.html", "class_nano_byte_1_1_common_1_1_math_utils" ],
        [ "NotAdminException", "class_nano_byte_1_1_common_1_1_not_admin_exception.html", "class_nano_byte_1_1_common_1_1_not_admin_exception" ],
        [ "ProcessUtils", "class_nano_byte_1_1_common_1_1_process_utils.html", "class_nano_byte_1_1_common_1_1_process_utils" ],
        [ "PropertyPointer", "class_nano_byte_1_1_common_1_1_property_pointer.html", "class_nano_byte_1_1_common_1_1_property_pointer" ],
        [ "StagedOperation", "class_nano_byte_1_1_common_1_1_staged_operation.html", "class_nano_byte_1_1_common_1_1_staged_operation" ],
        [ "StringUtils", "class_nano_byte_1_1_common_1_1_string_utils.html", "class_nano_byte_1_1_common_1_1_string_utils" ],
        [ "TimedLogEvent", "struct_nano_byte_1_1_common_1_1_timed_log_event.html", "struct_nano_byte_1_1_common_1_1_timed_log_event" ],
        [ "UpdateUtils", "class_nano_byte_1_1_common_1_1_update_utils.html", "class_nano_byte_1_1_common_1_1_update_utils" ],
        [ "AnsiCli", "class_nano_byte_1_1_common_1_1_ansi_cli.html", "class_nano_byte_1_1_common_1_1_ansi_cli" ]
      ] ]
    ] ]
];