//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanoByte.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NanoByte.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection cannot be added to itself..
        /// </summary>
        public static string CannotAddCollectionToSelf {
            get {
                return ResourceManager.GetString("CannotAddCollectionToSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DACL cannot be canonicalized since it would potentially result in a loss of information..
        /// </summary>
        public static string CannotCanonicalizeDacl {
            get {
                return ResourceManager.GetString("CannotCanonicalizeDacl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Comment:.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files.
        /// </summary>
        public static string CopyFiles {
            get {
                return ResourceManager.GetString("CopyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy to clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination directory already exists..
        /// </summary>
        public static string DestinationDirExist {
            get {
                return ResourceManager.GetString("DestinationDirExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you whish, you can use this field to provide additional information about the problem, such as a description of what you were doing when the crash occurred..
        /// </summary>
        public static string ErrorReporComment {
            get {
                return ResourceManager.GetString("ErrorReporComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error report.
        /// </summary>
        public static string ErrorReport {
            get {
                return ResourceManager.GetString("ErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do &amp;not report.
        /// </summary>
        public static string ErrorReportCancel {
            get {
                return ResourceManager.GetString("ErrorReportCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred in this application. You can help us fix the problem by reporting it. If there is already a known fix for your problem it will be displayed right after sending the report..
        /// </summary>
        public static string ErrorReportInfo {
            get {
                return ResourceManager.GetString("ErrorReportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Report.
        /// </summary>
        public static string ErrorReportSend {
            get {
                return ResourceManager.GetString("ErrorReportSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error report was sent successfully..
        /// </summary>
        public static string ErrorReportSent {
            get {
                return ResourceManager.GetString("ErrorReportSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download {0}..
        /// </summary>
        public static string FailedToDownload {
            get {
                return ResourceManager.GetString("FailedToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open registry subkey &apos;{0}&apos; in &apos;{1}&apos;..
        /// </summary>
        public static string FailedToOpenRegistrySubkey {
            get {
                return ResourceManager.GetString("FailedToOpenRegistrySubkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rollback &apos;{0}&apos;..
        /// </summary>
        public static string FailedToRollback {
            get {
                return ResourceManager.GetString("FailedToRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start &apos;{0}&apos;..
        /// </summary>
        public static string FailedToStart {
            get {
                return ResourceManager.GetString("FailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file that was supposed to be downloaded from {0} doesn&apos;t have the expected size. Was supposed to be {1} bytes but was actually {2} bytes..
        /// </summary>
        public static string FileNotExpectedSize {
            get {
                return ResourceManager.GetString("FileNotExpectedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; could not be found..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration directory &apos;{0}&apos; is probably invalid..
        /// </summary>
        public static string InvalidConfigDir {
            get {
                return ResourceManager.GetString("InvalidConfigDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login credentials for {0} are incorrect..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key was already present in the dictionary..
        /// </summary>
        public static string KeyAlreadyPresent {
            get {
                return ResourceManager.GetString("KeyAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching &apos;{0}&apos; requires Administrator privileges..
        /// </summary>
        public static string LaunchNeedsAdmin {
            get {
                return ResourceManager.GetString("LaunchNeedsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum amount of elements in the collection has been exceeded..
        /// </summary>
        public static string MaxElementsExceeded {
            get {
                return ResourceManager.GetString("MaxElementsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No action registered for &apos;{0}&apos;..
        /// </summary>
        public static string MissingDispatchAction {
            get {
                return ResourceManager.GetString("MissingDispatchAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System configuration cannot be edited in portable mode..
        /// </summary>
        public static string NoSystemConfigInPortableMode {
            get {
                return ResourceManager.GetString("NoSystemConfigInPortableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is only available on Windows..
        /// </summary>
        public static string OnlyAvailableOnWindows {
            get {
                return ResourceManager.GetString("OnlyAvailableOnWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter login credentials for {0}:.
        /// </summary>
        public static string PleaseEnterCredentials {
            get {
                return ResourceManager.GetString("PleaseEnterCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading &apos;{0}&apos;..
        /// </summary>
        public static string ProblemLoading {
            get {
                return ResourceManager.GetString("ProblemLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; exited with exit code {1}..
        /// </summary>
        public static string ProcessExitCode {
            get {
                return ResourceManager.GetString("ProcessExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A process exited with an unexpected exit code..
        /// </summary>
        public static string ProcessExitCodeUnexpected {
            get {
                return ResourceManager.GetString("ProcessExitCodeUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading file {0}.
        /// </summary>
        public static string ReadingFile {
            get {
                return ResourceManager.GetString("ReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be performed again until the undo command has been performed..
        /// </summary>
        public static string RedoNotAvailable {
            get {
                return ResourceManager.GetString("RedoNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset value.
        /// </summary>
        public static string ResetValue {
            get {
                return ResourceManager.GetString("ResetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting applications.
        /// </summary>
        public static string RestartingApps {
            get {
                return ResourceManager.GetString("RestartingApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for open file references.
        /// </summary>
        public static string SearchingFileReferences {
            get {
                return ResourceManager.GetString("SearchingFileReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to read from position {0}. This is {1} bytes away from the underlying stream position {2}, but the seek buffer can only accomodate a difference of {3} bytes..
        /// </summary>
        public static string SeekOffsetTooLarge {
            get {
                return ResourceManager.GetString("SeekOffsetTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down applications.
        /// </summary>
        public static string ShuttingDownApps {
            get {
                return ResourceManager.GetString("ShuttingDownApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and destination are equal..
        /// </summary>
        public static string SourceDestinationEqual {
            get {
                return ResourceManager.GetString("SourceDestinationEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string StateComplete {
            get {
                return ResourceManager.GetString("StateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing data.
        /// </summary>
        public static string StateData {
            get {
                return ResourceManager.GetString("StateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting headers.
        /// </summary>
        public static string StateHeader {
            get {
                return ResourceManager.GetString("StateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO error.
        /// </summary>
        public static string StateIOError {
            get {
                return ResourceManager.GetString("StateIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string StateReady {
            get {
                return ResourceManager.GetString("StateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web error.
        /// </summary>
        public static string StateWebError {
            get {
                return ResourceManager.GetString("StateWebError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of targets must be equal to Length of oldValues.
        /// </summary>
        public static string TargetsOldValuesLength {
            get {
                return ResourceManager.GetString("TargetsOldValuesLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical details:.
        /// </summary>
        public static string TechnicalDetails {
            get {
                return ResourceManager.GetString("TechnicalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version of .NET does not support TLS 1.2. This may cause connection errors when downloading content via HTTPS. Please run Windows Update to install the necessary patches..
        /// </summary>
        public static string Tls12SupportMissing {
            get {
                return ResourceManager.GetString("Tls12SupportMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly named &quot;{0}&quot; could not be located..
        /// </summary>
        public static string UnableToLocateAssembly {
            get {
                return ResourceManager.GetString("UnableToLocateAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read {0} bytes from the stream..
        /// </summary>
        public static string UnableToReadBytesFromStream {
            get {
                return ResourceManager.GetString("UnableToReadBytesFromStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This undo command cannot be performed until the actual command has been performed..
        /// </summary>
        public static string UndoNotAvailable {
            get {
                return ResourceManager.GetString("UndoNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Unix subsystem failed to process the request. You may have insufficient rights..
        /// </summary>
        public static string UnixSubsystemFail {
            get {
                return ResourceManager.GetString("UnixSubsystemFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
