
// This file has been generated by the GUI designer. Do not modify.
namespace NanoByte.Common.Tasks
{
	internal partial class TaskRunDialog
	{
		private global::Gtk.VBox vBoxInner;
		private global::Gtk.ProgressBar progressBarTask;
		private global::Gtk.Label labelTask;
		private global::Gtk.Button buttonCancel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NanoByte.Common.Tasks.TaskRunDialog
			this.Name = "NanoByte.Common.Tasks.TaskRunDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child NanoByte.Common.Tasks.TaskRunDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "vBox";
			w1.BorderWidth = ((uint)(2));
			// Container child vBox.Gtk.Box+BoxChild
			this.vBoxInner = new global::Gtk.VBox ();
			this.vBoxInner.Name = "vBoxInner";
			this.vBoxInner.Spacing = 10;
			this.vBoxInner.BorderWidth = ((uint)(10));
			// Container child vBoxInner.Gtk.Box+BoxChild
			this.progressBarTask = new global::Gtk.ProgressBar ();
			this.progressBarTask.Name = "progressBarTask";
			this.vBoxInner.Add (this.progressBarTask);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vBoxInner [this.progressBarTask]));
			w2.Position = 0;
			// Container child vBoxInner.Gtk.Box+BoxChild
			this.labelTask = new global::Gtk.Label ();
			this.labelTask.Name = "labelTask";
			this.vBoxInner.Add (this.labelTask);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vBoxInner [this.labelTask]));
			w3.Position = 1;
			w1.Add (this.vBoxInner);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.vBoxInner]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Internal child NanoByte.Common.Tasks.TaskRunDialog.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "actionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child actionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonCancel]));
			w6.Expand = false;
			w6.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 150;
			this.Show ();
		}
	}
}
